name = "FunctionalBayesExtremes"
uuid = "d5bf9f5e-4818-497f-9f1b-418edfd156b8"
authors = ["Max Thannheimer"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
